/**
 * Build-time script: converts SEO.csv → src/data/seo-products.ts
 *
 * Uses a minimal RFC-4180 state-machine parser (no csv-parse/papaparse).
 * The CSV contains multi-line quoted Description fields — never split on comma.
 *
 * Run: npx tsx src/scripts/build-seo-data.ts
 */

import fs from 'node:fs';
import path from 'node:path';

const CSV_PATH = path.resolve(process.cwd(), 'SEO.csv');
const OUT_PATH = path.resolve(process.cwd(), 'src/data/seo-products.ts');

// ── RFC-4180 state-machine CSV parser ────────────────────────────────────────

function parseCsv(raw: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = '';
  let inQuote = false;

  for (let i = 0; i < raw.length; i++) {
    const ch = raw[i];
    const next = raw[i + 1];

    if (inQuote) {
      if (ch === '"' && next === '"') {
        field += '"';
        i++;
      } else if (ch === '"') {
        inQuote = false;
      } else {
        field += ch;
      }
    } else {
      if (ch === '"') {
        inQuote = true;
      } else if (ch === ',') {
        row.push(field);
        field = '';
      } else if (ch === '\r' && next === '\n') {
        row.push(field);
        field = '';
        rows.push(row);
        row = [];
        i++;
      } else if (ch === '\n') {
        row.push(field);
        field = '';
        rows.push(row);
        row = [];
      } else {
        field += ch;
      }
    }
  }
  // flush last field/row
  if (field !== '' || row.length > 0) {
    row.push(field);
    rows.push(row);
  }
  return rows;
}

// ── Parse + map ───────────────────────────────────────────────────────────────

const raw = fs.readFileSync(CSV_PATH, 'utf-8');
const [headerRow, ...dataRows] = parseCsv(raw);

function idx(name: string): number {
  const i = headerRow.indexOf(name);
  if (i === -1) throw new Error(`Column "${name}" not found in CSV headers`);
  return i;
}

const COL = {
  cardCode:         idx('Card Code'),
  category:         idx('Card Category'),
  title:            idx('Title'),
  h1:               idx('H1 Content'),
  description:      idx('Description'),
  metaDescription:  idx('Meta Description'),
  primaryKeyword:   idx('Primary Keyword'),
  secondaryKeywords:idx('Secondary Keywords'),
  imageAlt:         idx('Image Alt Text'),
  imageFileName:    idx('Image File name'),
  urlSlug:          idx('URL Slug'),
};

interface SeoProduct {
  cardCode: string;
  category: string;
  title: string;
  h1: string;
  description: string;
  metaDescription: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  imageAlt: string;
  imageFileName: string;
  slug: string;
}

const products: SeoProduct[] = dataRows
  .filter((row) => row.length > COL.urlSlug && row[COL.cardCode].trim() !== '')
  .map((row) => ({
    cardCode:          row[COL.cardCode].trim(),
    category:          row[COL.category].trim(),
    title:             row[COL.title].trim(),
    h1:                row[COL.h1].trim(),
    description:       row[COL.description].trim(),
    metaDescription:   row[COL.metaDescription].trim(),
    primaryKeyword:    row[COL.primaryKeyword].trim(),
    secondaryKeywords: row[COL.secondaryKeywords].split(',').map((s) => s.trim()).filter(Boolean),
    imageAlt:          row[COL.imageAlt].trim(),
    imageFileName:     row[COL.imageFileName].trim(),
    slug:              row[COL.urlSlug].trim().replace(/^\/product\//, ''),
  }));

// ── Generate TypeScript output ────────────────────────────────────────────────

const lines: string[] = [
  '// AUTO-GENERATED by src/scripts/build-seo-data.ts — do not edit manually.',
  '// Source: SEO.csv',
  '',
  'export interface SeoProduct {',
  '  cardCode: string;',
  '  category: string;',
  '  title: string;',
  '  h1: string;',
  '  description: string;',
  '  metaDescription: string;',
  '  primaryKeyword: string;',
  '  secondaryKeywords: string[];',
  '  imageAlt: string;',
  '  imageFileName: string;',
  '  slug: string;',
  '}',
  '',
  'export const SEO_PRODUCTS: readonly SeoProduct[] = Object.freeze([',
];

for (const p of products) {
  lines.push('  {');
  lines.push(`    cardCode: ${JSON.stringify(p.cardCode)},`);
  lines.push(`    category: ${JSON.stringify(p.category)},`);
  lines.push(`    title: ${JSON.stringify(p.title)},`);
  lines.push(`    h1: ${JSON.stringify(p.h1)},`);
  lines.push(`    description: ${JSON.stringify(p.description)},`);
  lines.push(`    metaDescription: ${JSON.stringify(p.metaDescription)},`);
  lines.push(`    primaryKeyword: ${JSON.stringify(p.primaryKeyword)},`);
  lines.push(`    secondaryKeywords: ${JSON.stringify(p.secondaryKeywords)},`);
  lines.push(`    imageAlt: ${JSON.stringify(p.imageAlt)},`);
  lines.push(`    imageFileName: ${JSON.stringify(p.imageFileName)},`);
  lines.push(`    slug: ${JSON.stringify(p.slug)},`);
  lines.push('  },');
}

lines.push(']);', '');

lines.push('export const SEO_BY_SLUG: Readonly<Record<string, SeoProduct>> = Object.freeze(');
lines.push('  Object.fromEntries(SEO_PRODUCTS.map((p) => [p.slug, p]))');
lines.push(');', '');

lines.push('export const SEO_BY_CARD_CODE: Readonly<Record<string, SeoProduct>> = Object.freeze(');
lines.push('  Object.fromEntries(SEO_PRODUCTS.map((p) => [p.cardCode.toUpperCase(), p]))');
lines.push(');', '');

fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, lines.join('\n'), 'utf-8');

console.log(`✓ Wrote ${products.length} SEO products to ${OUT_PATH}`);
